project:
  type: website
  execute-dir: project

jupyter: python3

resources:
  - "data/*"

website:
  title: "Introduction to Data Analysis in Python"
  page-navigation: true

  sidebar: 
    title: "Introduction to Data Analysis in Python"
    logo: "assets/UoB_RGB_24.png"
    align: center
    logo-alt: "University of Bristol logo"
    style: "docked"
    border: true
    contents: 
      - index.qmd
      - auto: "pages/*qmd"

  page-footer:
     left: "[Jean Golding Institute](https://www.bristol.ac.uk/golding/) © [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"  
  
  repo-url: https://github.com/bristol-training/introduction-to-data-analysis-in-python
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    shift-heading-level-by: 1
    highlight-style: github

execute:
  freeze: auto
  error: true
